### ISSUE TITLE
Issue with word_to_line

### ISSUE THREAD

**Issue by taylor-arnold** [EmilHvitfeldt/ggpage#3]
Currently, the `word_to_line` function does not seem to work as expected whenever
the `wot_number` exceeds the length of the input. For example, you would expect
this to list the letters in order, but instead they are shuffled across lines:

```{r}
word_to_line(data.frame(text = LETTERS), wot_number = 10)
```
```
                  1                   2                   3 
"A D G J M P S V Y" "B E H K N Q T W Z"   "C F I L O R U X" 
```
I think I see where the issue and and will submit a pull request to fix it.

**Comment by EmilHvitfeldt** [comment]
oh wow, that is quite a strange bug, happy you found it!
