### ISSUE TITLE
changes to sentiment lexicon

### ISSUE THREAD

**Issue by juliasilge** [EmilHvitfeldt/ggpage#9]
Hello! 👋 

I am going through tidytext's reverse dependencies and discovered that ggpage uses the NRC lexicon in sentiment analysis. As you are aware, we've done a re-examination of the decision to include so many sentiment lexicons within tidytext in juliasilge/tidytext#131, because of how the lexicons have various licenses and tidytext has a *different* license, and the NRC lexicon is no longer going to be included in the package. 😕

This new version of tidytext is going to be submitted to CRAN in about a week or so, and after that the Bing lexicon will be the only one available directly in tidytext. I want to a) let you know so you can work on updates and b) apologize for how this chain of decisions impacts you! Let me know if you have questions or if I can help.

**Comment by EmilHvitfeldt** [comment]
Thank you! new version on CRAN have issues fixed
